// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emfqqfstmavfaflnjrvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtZnFxZnN0bWF2ZmFmbG5qcnZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NzU3NDAsImV4cCI6MjA2OTQ1MTc0MH0._71Sq294sLmYD1DxhB10FUn04E9HdpzvHYCjDKZKUSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});